# Generated by Django 4.0.6 on 2022-11-14 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bangjob',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='chenjob',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='hydjob',
            old_name='adress',
            new_name='address',
        ),
    ]
