# Generated by Django 4.0.6 on 2022-11-14 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_rename_adress_bangjob_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bangjob',
            old_name='phonenumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='chenjob',
            old_name='phonenumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='hydjob',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
